trigger:
- master

variables:
- group: global-vars

stages:
- stage: CI
  displayName: CI - Stage
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Preparation

    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.15.4'
      displayName: 'Terraform install'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
        backendServiceArm: 'Development'
        backendAzureRmResourceGroupName: '$(RESOURCE_GROUP_NAME)'
        backendAzureRmStorageAccountName: '$(STORAGE_ACCOUNT_NAME)'
        backendAzureRmContainerName: '$(CONTAINER_NAME)'
        backendAzureRmKey: '$(STORAGE_KEY)'
      displayName: 'Terraform init'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
      displayName: 'Terraform validate'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
        commandOptions: '-var-file=vars_pro.tfvars -out=plan.tfplan'
        environmentServiceNameAzureRM: 'Development'
      displayName: 'Terraform plan'

- stage: CD
  displayName: CD - Stage
  jobs:
  - deployment: Deploy
    continueOnError: false
    environment: 'Development IaC'
    strategy:
      runOnce:
        deploy:      
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                echo 'Hello world'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(System.DefaultWorkingDirectory)/terraform/'
#     Contents: '**'
#     TargetFolder: '$(Build.Artifactstagingdirectory)'
#   displayName: 'Copy terraform plan to artifacts'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'terraform'
#     publishLocation: 'Container'
#   displayName: 'Publish terraform plan'
